# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ releases/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
          java-version: 11

      - name: Get branch initial commit tag
        id: release
        shell: bash
        run: |
          echo "The current branch is ${GITHUB_REF#refs/heads/}"
          releaseBranch=$(git rev-parse --abbrev-ref HEAD | sed 's/.*\/\(.*\)/\1/')
          echo "::set-output name=release_branch::$releaseBranch"

      - uses: actions/checkout@v2.3.1
        with:
          ref: ${{ steps.release.outputs.release_branch }}

      - name: Calculating fix number
        id: manager
        shell: bash
        env:
          VERSION: ${{ steps.release.outputs.release_branch }}
        run: |
          git checkout ${GITHUB_REF#refs/heads/}
          commits=$(git rev-list --count refs/tags/$VERSION..HEAD)
          echo "You are $commits commits ahead in this branch"
          echo "VERSION_NAME=$VERSION.$commits" >> $GITHUB_ENV
          echo "::set-output name=version_name::$VERSION_NAME"

      - name: Set library version to deploy
        shell: bash
        run: sed -i -e 's/pom.version=[0-9]*.[0-9]*.[0-9]*/pom.version='${VERSION_NAME}'/g' ./navigation/gradle.properties

      - name: Generate GPG Key file
        shell: bash
        env:
          CONTENT: ${{ secrets.SIGNING_SECRET_KEY_RING_CONTENT }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          printf "$CONTENT" | base64 --decode > ./navigation/private.key
          gpg --batch --import ./navigation/private.key
          echo "signing.keyId=$SIGNING_KEY_ID" >> ./navigation/local.properties
          echo "signing.password=$SIGNING_PASSWORD" >> ./navigation/local.properties
          echo "signing.secretKeyRingFile=./private.key" >> ./navigation/local.properties

      - name: Sending to Maven Central
        uses: eskatos/gradle-command-action@v1
        env:
          PUBLISH_USERNAME: ${{secrets.MAVEN_CENTRAL_USER}}
          PUBLISH_PASSWORD: ${{secrets.MAVEN_CENTRAL_TOKEN}}
        with:
          arguments: "-Dorg.gradle.internal.http.socketTimeout=300000 -Dorg.gradle.internal.http.connectionTimeout=300000 navigation:publish"

      - name: Confirming release on Maven Central
        uses: eskatos/gradle-command-action@v1
        env:
          PUBLISH_USERNAME: ${{secrets.MAVEN_CENTRAL_USER}}
          PUBLISH_PASSWORD: ${{secrets.MAVEN_CENTRAL_TOKEN}}
          PUBLISH_PROFILE: ${{secrets.MAVEN_CENTRAL_PROFILE}}
        with:
          arguments: "closeAndReleaseRepository"

      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.manager.outputs.version_name }}
          release_name: ${{ steps.manager.outputs.version_name }}

      - name: Tag release
        shell: bash
        env:
          VERSION: ${{ steps.release.outputs.release_branch }}
        run: |
          git tag $VERSION
          git push origin $VERSION

      - name: Remove GPG file
        shell: bash
        run: |
          rm -f ./navigation/signature.gpg
          rm -f ./navigation/local.properties
