# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ releases/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.1
        with:
          ref: develop

      - uses: actions/checkout@v2.3.1

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
          java-version: 1.9

      - name: Get fix number
        shell: bash
        run: |
          commits=$(git rev-list --count refs/remotes/origin/develop..HEAD)
          echo "::set-env name=FIX_NUMBER::$commits"

      - name: Get current library version
        shell: bash
        run: |
          IFS='/' read -ra strarr <<< "${GITHUB_REF#refs/heads/}"
          version="${strarr[1]}".$FIX_NUMBER
          echo "::set-env name=VERSION_NAME::$version"

      - name: Set library version to deploy
        shell: bash
        run: sed -i -e 's/pom.version=[0-9]*.[0-9]*.[0-9]*/pom.version='${VERSION_NAME}'/g' ./navigation/gradle.properties

      - name: Create a Release
        uses: actions/create-release@v1
        with:
          tag_name: $VERSION_NAME
          release_name: $VERSION_NAME

      - name: Gradle Command
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "navigation:publish"
