# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ releases/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
          java-version: 1.9

      - name: Get current library version
          shell: bash
          run: echo "::set-env name=VERSION_NAME::./gradlew navigation:pomVersion"

      - name: Print version
          shell: bash
          run: echo "Version is ${VERSION_NAME}"

      - name: Release notes generator
        uses: Decathlon/release-notes-generator-action@v2.1.0
#
#      - name: Create a Release
#        uses: actions/create-release@v1
#        with:
#          tag_name:
#          # The name of the release. For example, `Release v1.0.1`
#          release_name:
#          # Text describing the contents of the tag.
#          body: # optional
#          # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
#          draft: # optional
#          # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
#          prerelease: # optional
#
#      - name: Gradle Command
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: "navigation:publish"
